#pragma once

#include <px4_platform_common/module.h>
#include <px4_platform_common/module_params.h>
#include <px4_platform_common/px4_work_queue/ScheduledWorkItem.hpp>

#include <matrix/matrix/math.hpp>

#include <uORB/Publication.hpp>
#include <uORB/Subscription.hpp>

#include <uORB/topics/vehicle_local_position.h>
#include <uORB/topics/vehicle_angular_velocity.h>
#include <uORB/topics/vehicle_attitude.h>
#include <uORB/topics/fvso_state.h>
#include <uORB/topics/servo_angle_real_state.h>

struct MeasurementStates
{
	/* The defined states of the FWMAV captured by the sensors */
	/* u: body linear velocities along x-axis , get through vehicle_local_position
	   w: body linear velocities along z-axis , get through vehicle_local_position
	   q: body pitch angular velocity , get through vehicle_angular_velocity
	   theta：pitch angle , get through vehicle_attitude  */
	float u;
	float w;
	float q;
	float theta;
};

struct LinearizedDynamicModel
{
	/* Parameter matrix for building a flight vehicle dynamics model */
	/* Obtained offline through neural networks and system identification */
	/* A_l and B_e should be determined before the Fvso runs */
	matrix::Matrix<float,4,4> A_l;
	matrix::Matrix<float,4,1> B_e;
	/* Q_l represents the covariance matrix of the process noise
	which should be adjusted according to the actual situation*/
	matrix::Vector<float,4> Q_l_diag;
	/* Gamma_l represents the process noise input model
	But it is still unclear whether this is an adjustable parameter.*/
	matrix::Matrix<float, 4, 4> Gamma_l;
	matrix::Vector<float,4> R_l_diag;

};

struct GFVChannelParams
{
	/* Transfer function parameters used to build the noise model */
	/* Which should be adjusted according to the actual situation*/
	/* For detailed meanings, refer to Table 4 in the paper */
	float a;
    	float b;
    	float epsilon;
    	float omega;
};

struct FlappingVibrationModel
{
	/* The white noise from each channel goes through its own corresponding second-order model
	(the parameters might be different for each channel) to produce the final noise model. */
	GFVChannelParams GFV_u;
	GFVChannelParams GFV_w;
	GFVChannelParams GFV_q;
	GFVChannelParams GFV_theta;
	/* Since the paper already assumes the four channels are independent,
	Qn is simplified into a diagonal matrix.
	The vector form defined here is just used to simplify parameter tuning and matrix construction.*/
	matrix::Vector<float,4> Q_n_diag;
};

struct ContinuousModelMatrices
{
	/* Construct the parameter matrix in the continuous form
	for the construction of the parameter matrix in the discrete form */
	/* Flapping vibration model: Eq.(46) */
	/* Generated by FlappingVibrationModel */
	matrix::Matrix<float, 8, 8> A_n;
	matrix::Matrix<float, 8, 4> B_n;
	matrix::Matrix<float, 4, 8> C_n;

	/* Extended model: Eq.(47) */
	/* Generated by FlappingVibrationModel and LinearizedDynamicModel*/
	matrix::Matrix<float, 12, 12> A_ex;
	matrix::Matrix<float, 12, 1>  B_ex;
	matrix::Matrix<float, 4, 12>  C_ex;
	/* Process-noise related matrices */
	matrix::Matrix<float, 12, 8> Gamma_ex;
	matrix::Matrix<float, 8, 8>  Q_ex;
};

struct DiscreteFormMatrices
{
	/* The discrete form of constant Matrices utilized in the calculation of the Fvso */
	/* The size of the Matrices and vectors needs to be carefully confirmed*/
	matrix::Matrix<float, 12, 12> A_ex_s;
    	matrix::Matrix<float, 12, 1>  B_ex_s;
    	matrix::Matrix<float, 4, 12>  C_ex_s;
    	matrix::Matrix<float, 12, 12> Q_ex_s;
    	matrix::Matrix<float, 4, 4>   R_l_s;
	matrix::Matrix<float, 12, 12> A_ex_s_T;
	matrix::Matrix<float, 12, 4> C_ex_s_T;
};

struct InnerVariables
{
	/* The inner variables utilized in the calculation of the Fvso */
	/* The size of the Matrices and vectors needs to be confirmed*/
	matrix::Vector<float,12> x_pred;
	matrix::Vector<float,12> x_est;

	matrix::Matrix<float,12,12> p_pred;
	matrix::Matrix<float,12,12> p_est;
	matrix::Matrix<float,12,12> p_0;

	matrix::Matrix<float,12,4> K;

	bool Init;
};


class Fvso :
	public ModuleBase<Fvso>,
	public ModuleParams,
	public px4::ScheduledWorkItem
{
private:

	void Run() override;

	/* ------------------- The specific implementation of FVSO ------------------ */
	/* The realiaztion of FVSO can be divided into three parts */
	void Initialization(const MeasurementStates &z);
	void Prediction(float equ_pitch_input);
	bool Estimation(const MeasurementStates &z);

	/* Get inputs of Fvso: Sensor data(z(k)) and Equivalent pithch control input(equ_pitch_input) */
	bool UpdateSensorDatas(MeasurementStates &z);
	bool UpdateEquPitchInput(float &equ_pitch_input);

	/* The outputs of Fvso: The Xl of Xes will be used by controller */
	void PublishState();

	/* ---------------------- Build Model Parameters --------------------- */
	/* Build the flapping vibration state-space model Eq.(46)
	   from GFV parameters in Eq.(42) */
	void BuildFlappingVibrationModel();

	/* Combine the linearized aircraft dynamic model Eq.(44)
	   and flapping vibration model Eq.(46)
	   to build the extended continuous model Eq.(47) */
	void BuildExtendedModel();

	/* ------------------------ Build DiscreteFormMatrices ----------------------- */
	/* Build DiscreteFormMatrices through Eq.(49) to Eq.(54)*/
	void BuildDiscreteFormMatrices();

	/* ---------------------------- Basic Parameters ---------------------------- */
	/* Base parameters */
	LinearizedDynamicModel FVSO_DynamicModel;
	FlappingVibrationModel FVSO_FlappingModel;

	/* Continuous matrices constructed from base parameters */
	ContinuousModelMatrices FVSO_ContinuousMatrices;

	/* Discretized matrices used by FVSO */
	DiscreteFormMatrices FVSO_DiscreteFormMatrices;

	/* Runtime variables */
	InnerVariables FVSO_InnerVariables;

	/* FVSO sample time of the discretized system */
	static constexpr float FVSO_SAMPLE_TIME{0.004f};

	/*Initialization parameters */
	void InitializeParams();

	/* Load params of the GFV channel */
	static void LoadGFVParams(GFVChannelParams &target,
			float a,
			float b,
			float epsilon,
			float omega);

	/* Check params for safety reasons */
	bool ValidateParams() const;

	/* ---------------------------- Connections with PX4 ---------------------------- */
	/* Get inputs by PX4: Sensor data(z(k)) and Equivalent pithch control input(equ_pitch_input) */
	/* ------------------------------ Sensor Datas ------------------------------ */
	/* u, w: estimated velocity, later will be transformed to body frame */
    	uORB::Subscription _vehicle_local_position_sub{ORB_ID(vehicle_local_position)};
	/* q: body angular velocity */
    	uORB::Subscription _vehicle_angular_velocity_sub{ORB_ID(vehicle_angular_velocity)};
	/* theta: attitude quaternion -> pitch angle */
    	uORB::Subscription _vehicle_attitude_sub{ORB_ID(vehicle_attitude)};
	/* Get real servo angle as Equ_input */
	uORB::Subscription _servo_angle_real_state_sub{ORB_ID(servo_angle_real_state)};

	/* Cache the latest data from each required PX4 topic */
	vehicle_local_position_s _vehicle_local_position{};
	vehicle_angular_velocity_s _vehicle_angular_velocity{};
	vehicle_attitude_s _vehicle_attitude{};

	/* Record whether each topic has been updated since the last complete z(k) was used */
	bool _local_position_updated{false};
	bool _angular_velocity_updated{false};
	bool _attitude_updated{false};

	/* Get EquPitchInput */

	/* Publish states by PX4: Publish states to controller */
	uORB::Publication<fvso_state_s> _fvso_state_pub{ORB_ID(fvso_state)};

	/* ------------ To optimize the stack space during matrix runtime ----------- */
	matrix::Matrix<float, 4, 12> _CP;
	matrix::Matrix<float, 12, 4> _PCt;

	matrix::SquareMatrix<float, 4> _innovation_cov;
	matrix::SquareMatrix<float, 4> _innovation_cov_inv;

	matrix::Vector<float, 4> _innovation;
public:
	Fvso();
	~Fvso() override;

	static int task_spawn(int argc, char *argv[]);
	static int custom_command(int argc, char *argv[]);
	static int print_usage(const char *reason = nullptr);

	bool init();

	int print_status() override;
};
